Repository magestat/magento2-split-order, pull requests merged in 2019-05, with the labels that each got.

#21 Issue #16 and #20: Fix issue with totals & Improve PHPDocs
  Api/QuoteHandlerInterface.php
  Block/Checkout/Success.php
  Helper/Data.php
  Model/Config/Source/Attributes.php
  Model/QuoteHandler.php
  Plugin/SplitQuote.php
Labels: bug, enhancement

#25 [#24] Fix attribute value response
  Api/QuoteHandlerInterface.php
  Model/QuoteHandler.php
Labels: bug

#27 [26] Split Order Based on the product Stock Status
  Api/ExtensionAttributesInterface.php
  Api/QuoteHandlerInterface.php
  Block/Checkout/Success.php
  Helper/Data.php
  Model/Config/Source/AttributeQty.php
  Model/Config/Source/Attributes.php
  Model/ExtensionAttributes.php
  Model/QuoteHandler.php
  Plugin/SplitQuote.php
  etc/adminhtml/system.xml
  etc/di.xml
Labels: enhancement

#28 Create CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: enhancement
